# Generated by Django 5.2.3 on 2025-06-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='company',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(choices=[('Trainer', 'Trainer'), ('Student', 'Student'), ('Client', 'Client')], default='Student', max_length=20),
        ),
    ]
