# Generated by Django 5.2.3 on 2025-06-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_testimonial_company_alter_testimonial_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Python', 'Python'), ('Cybersecurity', 'Cybersecurity'), ('AI/ML', 'AI/ML'), ('Cloud', 'Cloud'), ('Data Science', 'Data Science'), ('Data Analytics', 'Data Analytics'), ('DevOps', 'DevOps'), ('Machine Learning', 'Machine Learning'), ('Deep Learning', 'Deep Learning'), ('Java', 'Java'), ('Java Script', 'Java Script'), ('Web Development', 'Web Development')], max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='default-blog.jpg', upload_to='blogs/')),
                ('author', models.CharField(default='Admin', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
